### ISSUE TITLE
Settings heading size incorrect

### ISSUE THREAD

**Issue by shaynesanderson-zz** [awesomemotive/edd-recently-viewed-items#10]
## Bug Report

When viewing the settings in "Downloads-->Settings-->Extensions", the heading size is not set correctly and is the same size as other sub headings.

Size should match "Per Product Emails" heading in the example below. 

<img width="1246" alt="Screen Shot 2021-01-27 at 14 01 25" src="https://user-images.githubusercontent.com/1680163/106049030-43512e80-60ab-11eb-9a0a-00764ffe064f.png">

**Comment by LisaCee** [comment]
PR #13
